"use client";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";
import { Inter } from "next/font/google";
import React from "react";
import { BrowserRouter as Router } from "react-router-dom";
import { AuthProvider } from "@/app/login/tokenContext";
import { MedicProvider } from '@/app/login/medicContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Router>
      <MedicProvider>
        <AuthProvider>
          <html lang="en">
            <body className={inter.className}>
              <Navbar />
              {children}
              <Footer />
            </body>
          </html>
        </AuthProvider>
      </MedicProvider>
    </Router>
  );
}
